# Generated by Django 3.0.5 on 2020-09-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pltest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musician', to='ExamApi.Place'),
        ),
    ]
