# Generated by Django 3.0.5 on 2020-09-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0004_auto_20200924_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cameramodel', models.CharField(max_length=50)),
                ('byyear', models.DateField()),
                ('pluse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_place', to='ExamApi.Place')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
