# Generated by Django 3.0.5 on 2020-09-25 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0006_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='Demo1',
        ),
    ]
