# Generated by Django 3.0.5 on 2020-09-29 05:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0008_auto_20200925_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('attrs', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.CharField(max_length=200)),
                ('nf', jsonfield.fields.JSONField()),
            ],
        ),
    ]
