# Generated by Django 3.0.5 on 2020-09-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0009_shopitem1_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseProductID', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Welcome',
        ),
        migrations.AddField(
            model_name='vote',
            name='Basevalue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamApi.Voter'),
        ),
    ]
