# Generated by Django 3.0.5 on 2020-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApi', '0011_mobileproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileproduct',
            name='Productid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
