# Generated by Django 3.0.5 on 2020-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eaddress',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
