# Generated by Django 3.0.5 on 2020-09-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_Api', '0002_auto_20200914_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
